In [4]:
import numpy as np


In [5]:
x=np.zeros((3,4))


In [6]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
x=np.ones((2,3,4), dtype='int16')

In [8]:
x

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [9]:
x=np.arange(10,25,5)

In [10]:
x

array([10, 15, 20])

In [11]:
x= np.linspace(0,2,9)

In [21]:
x

array([[0.16967402, 0.1672037 ],
       [0.76993899, 0.85482497]])

In [15]:
x=np.full((2,2),7)

In [16]:
x

array([[7, 7],
       [7, 7]])

In [17]:
x=np.eye(2,2)

In [18]:
x

array([[1., 0.],
       [0., 1.]])

In [19]:
x=np.random.random((2,2))

In [20]:
x

array([[0.16967402, 0.1672037 ],
       [0.76993899, 0.85482497]])

In [22]:
x=np.array([[2,4,6],[8,5,6]])

In [23]:
x

array([[2, 4, 6],
       [8, 5, 6]])

In [24]:
i=np.transpose(x)

In [26]:
i

array([[2, 8],
       [4, 5],
       [6, 6]])

In [27]:
a=np.array([1,3,4])

In [28]:
b=np.array([2,3,5])

In [29]:
np.add(b,a)

array([3, 6, 9])

In [30]:
np.subtract(b,a)

array([1, 0, 1])